import XCTest

#if !canImport(ObjectiveC)
/// Without the Objective-C runtime there is no autorelease pool; run the body.
func autoreleasepool<Result>(invoking body: () throws -> Result) rethrows -> Result { try body() }
#endif

#if !canImport(Darwin)
// swift-corelibs-xctest has no NSObject `init()`. Suites also create other
// suites only to call their helpers, e.g. `OriginalApplicationActiveGameplayTests().sequence(...)`
// or `D().…` through a typealias. Every direct XCTestCase subclass in the
// portable tests gets the Darwin-style initializer here.
extension FixtureInflateTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalActiveGameplayTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalActorControlTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalActorHitsTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalActorInputTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalActorPhysicsTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalActorSchedulerTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationActiveBodyTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationActiveCommandsTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationActiveContactsTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationActiveGameplayTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationActiveGraphicsTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationActiveHUDTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationActiveLayoutTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationActiveLifecycleTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationActiveNoticesTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationActiveOutputTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationActivePhysicsTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationActiveRecordingTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationArtSetupTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationBootstrapTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationCatalogFullTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationCatalogInputsTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationCatalogSessionTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationDispatchEntryTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationDispatchPrefixTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationFirstDamageTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationFrontScreenTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationGameplayProjectionTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationGameplayProviderTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationGameplaySourceTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationGameplayTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationGraphicsTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationHostDeliveryContextTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationHostGameplayTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationHostLoadingTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationHostMatchLaunchTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationHostSessionTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationInitializedLoadingTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationInitializedMenuTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationInputTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationInterfaceInputsTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationIterationDeliveryTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationLoadedCharacterTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationLoadedCycleTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationLoadedLaunchTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationLoadedMenuTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationLoadedSelectionTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationLoadingPrefixTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationLoadingSessionTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationLoopContinuationTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationMenuInputsTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationMenuInputTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationMenuReturnTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationMessageLoopTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationObservedStartupTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationPausedGameplayTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationPoolTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationPreparedStartupPlatformTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationRecoveryTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationScreenBodyTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationServiceKeysTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationSettingsTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationStartupInputsTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationTextResponseTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationTimerTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationWindowInspectionTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalApplicationWindowStartupTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalArithmeticPrecisionTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalBackgroundTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalBitmapDrawingTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalBitmapFontTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalBitmapSurfaceLoadingTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalBootstrapTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalCalendarTimeTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalCatalogChecksumTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalCatalogDIBPixelsTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalCatalogPrecisionTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalCatalogSoundsTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalCatalogTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalCharacterAITests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalCharacterMenuMusicSurfaceTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalCharacterMenuSurfaceTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalCharacterScreenTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalContinuousGameplayTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalCoordinatePrecisionTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalCRTTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalDataTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalDecimalMaterializationTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalDemoMusicTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalDiagnosticNumberTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalDIBPixelsTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalFrameLoaderTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalFreshCharacterMenuTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalFreshLibraryMenuTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalFrontControlSettingsTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalFrontMenuCompletionTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalFrontMenuLoopTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalFrontMenuResourcesTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalFrontRecordingInfoTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalFrontScreenAlternateTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalFrontScreenBodyTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalFrontScreenPreludeTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalGameplayBodyTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalGameplayCameraTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalGameplayCommandsTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalGameplayContactsTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalGameplayControlTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalGameplayCPointsTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalGameplayDrawingTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalGameplayHitsTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalGameplayHUDTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalGameplayImpulsesTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalGameplayLifecycleTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalGameplayLinksTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalGameplayNoticesTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalGameplayOutputTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalGameplayPhysicsTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalGameplayResultLayoutTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalGameplayResultRecordingTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalGameplayReturnTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalGraphEventsTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalInitialInterfaceSurfaceTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalInitialInterfaceTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalInitializedGameplayTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalInitialLoadingTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalInitialPoolAndInterfaceTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalInputControlTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalInputStartupTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLibActorControlTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLibActorHitsTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLibCharacterRosterTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLibLoadingTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLibMatchPreparationTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLibMenuContinuationTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLibModeScreenTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLibSelectionCommandsTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLibSelectionStageTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLibStageCommandsTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLibStageModeTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLibSurfaceTextTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLibTeamTournamentBracketTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLibTeamTournamentPreparationTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLibTeamTournamentSetupTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLibTournamentArenaReleaseTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLibTournamentBracketTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLibTournamentPreparationTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLibTournamentSetupTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLibTransformTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLibWarFaultRejectionTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLibWarGraphicsErrorTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLibWarMusicErrorTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLibWarNullableBitmapTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLibWarPartialSurfaceTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLibWarPreparationTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLibWarRetainedScratchTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLibWarSetupTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLibWorldContactsTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLoadedCatalogFilesTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLoadedCatalogTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLoadingAudioTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLoadingFilesTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalLocalInputTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalMainMenuTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalMatchContinuationTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalMatchLaunchTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalMatchPreludeTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalMatchPreparationTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalMatchRoundTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalMatchSelectionTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalMeleeTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalMenuCharacterTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalMenuContentTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalMenuCycleTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalMenuInfoReadingTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalMenuInfoWritingTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalMenuLoadingTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalMenuPanelBitmapTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalMenuPanelDrawingTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalMenuPanelUpdateTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalMenuPresentationTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalMenuResourcesTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalMenuReturnTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalMenuSoundStartupTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalMenuStartupTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalMissionStageTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalModeLabelTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalModePanelScreenTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalModeScreenTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalModeSelectionTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalMovementTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalMusicPlaybackTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalNetworkClientTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalNetworkExitTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalNetworkMenuTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalNetworkNotificationTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalObjectInputTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalObjectTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalPausedGameplayTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalPlaybackInformationTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalPlaybackPrologueTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalPostDrawCommandsTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalPostDrawLifecycleTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalPostDrawOpointTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalPostDrawSlotPrefixTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalPostHUDNoticesTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalQueuedSoundTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalRandomInitializationTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalReceivedInputTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalReplayCompressionTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalReplayFileInputTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalReplayFileOutputTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalReplayInitializationTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalReplayPlaybackStartTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalReplayPlaybackTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalReplayTickTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalReplayWriterTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalRequestSlotWordTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalResultLayoutTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalResultRecordingTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalRetainedHistoryTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalSettingsLoadingTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalSettingsWritingTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalStageEndingTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalStageFinaleTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalStageTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalStartupAudioMenuCorpus { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalStartupAudioTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalStartupOutputTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalStartupPanelTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalStartupStorageTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalStateTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalSurfaceSourceColorsTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalWarBattleTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalWarDependenciesTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalWarSetupNativeTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalWaveLoaderTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalWindowInitializationTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalWindowInputTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalWindowLifecycleTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalWindowRequestExchangeTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalWinMainStartupTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalWorldCameraTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalWorldContactsTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalWorldControlTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalWorldCPointsTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalWorldDrawingTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalWorldHUDTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalWorldImpulsesTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalWorldLinksTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension OriginalWorldPhysicsTests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
extension PortableSHA256Tests { convenience init() { self.init(name: "helper", testClosure: { _ in }) } }
#endif
