#!/usr/bin/env python3
"""Recover151 literal UI rectangles from identified EXE assignments (static evidence).
The output is native resource metadata, not x86 instructions or an interpreter.
No execution snapshots/expected states are inputs. Every disassembled byte is
checked against the pinned PE before the limited constant analysis proceeds.
"""
import argparse
import hashlib
import re
import subprocess
from import_ntsd import DEFAULT_SOURCE, EXE_SHA256, ROOT
from inspect_original import PE


def extract():
    source=DEFAULT_SOURCE/'NTSD 2.4.exe';raw=source.read_bytes();assert hashlib.sha256(raw).hexdigest()==EXE_SHA256
    pe=PE(raw);assembly=subprocess.check_output(['xcrun','llvm-objdump','--disassemble','--x86-asm-syntax=intel',str(source)],text=True)
    registers={'ebx':0,'ebp':19,'edx':('bitmap',0x45119c),'eax':('bitmap',0x451190)}
    groups=[];next_pc=0x424A72
    for line in assembly.splitlines():
        match=re.match(r'\s*([0-9a-f]+):[ \t]+((?:[0-9a-f]{2}[ \t]+)+)(\S.*)',line)
        if not match:continue
        pc=int(match[1],16)
        if not 0x424A72<=pc<=0x426B95:continue
        code=bytes.fromhex(match[2]);assert pc==next_pc;next_pc+=len(code)
        offset=pe.offset(pc-pe.base);assert raw[offset:offset+len(code)]==code
        op,operands=match[3].split(None,1)
        if op=='push':assert operands.strip()=='0x1f50';continue
        assert op=='mov',(hex(pc),op,operands)
        destination,source=operands.strip().split(', ',1)
        if source in registers:value=registers[source]
        elif m:=re.fullmatch(r'dword ptr \[(0x[0-9a-f]+)\]',source):value=('bitmap',int(m[1],16))
        else:value=int(source,0)&0xFFFFFFFF
        if re.fullmatch(r'e[a-z]{2}',destination):registers[destination]=value;continue
        if 'esp' in destination:assert destination=='dword ptr [esp + 0x420]';continue
        m=re.fullmatch(r'dword ptr \[(e[a-z]{2}) \+ (0x[0-9a-f]+)\]',destination);assert m,(hex(pc),destination)
        pointer=registers[m[1]];assert isinstance(pointer,tuple) and isinstance(value,int)
        if not groups or groups[-1]['slot']!=pointer[1]:groups.append(dict(slot=pointer[1],writes=[]))
        groups[-1]['writes'].append((pc,int(m[2],16),value))
    assert next_pc==0x426B98 and len(groups)==9
    text=['// Generated by tools/extract_front_menu_rectangles.py from static PE constants.',
          '// EXE SHA-256: '+EXE_SHA256,
          '// Original field order x/y/width/height, then count. No runtime EXE dependency.',
          'enum OriginalFrontMenuRectangles {',
          '    struct Sheet { let slot: Int; let frames: [[Int32]] }',
          '    static let sheets: [Sheet] = [']
    count=0
    for group in groups:
        rows=group['writes'][:-1];last=group['writes'][-1]
        assert len(rows)%4==0 and last[1:]==(12,len(rows)//4)
        text.append(f'        .init(slot: 0x{group["slot"]:x}, frames: [')
        for i in range(len(rows)//4):
            fields=rows[i*4:i*4+4];assert [w[1] for w in fields]==[o+i*4 for o in (0x10,0x7e0,0xfb0,0x1780)]
            assert all(w[2]<0x80000000 for w in fields)
            text.append('            ['+', '.join(str(w[2]) for w in fields)+f'], // {fields[0][0]:x}..{fields[-1][0]:x}')
            count+=1
        text.append(f'        ]), // count at {last[0]:x}')
    assert count==151
    text.extend(['    ]','}']);return '\n'.join(text)+'\n'


def main():
    parser=argparse.ArgumentParser(description=__doc__);parser.add_argument('--check',action='store_true');args=parser.parse_args()
    path=ROOT/'native/Sources/NTSDCore/OriginalFrontMenuRectangles.swift';text=extract()
    if args.check:assert path.read_text()==text
    else:path.write_text(text)
    print('Verified static151 rectangles /9 sheets /613 field assignments against pinned EXE')

if __name__=='__main__':main()
